export const enum RoutePaths {
  WELCOME = '/welcome',
  HOME = '/',
  PROFILE = '/profile',
  STORAGE = '/storage',
  SHARED = '/shared',
  SETTINGS = '/settings',
  SETTINGS_GENERAL = '/settings/general',
  SETTINGS_ACCOUNT = '/settings/account',
  SETTINGS_APPEARANCE = '/settings/appearance',
  HELP = '/help',
  LOGIN = '/auth/login',
  REGISTER = '/auth/register',
  FOLDER = '/folder',
}
