// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "Navbar": {
    "home": "Home",
    "profile": "Profile",
    "storage": "Storage",
    "shared": "Shared files",
    "settings": "Settings",
    "settingsGeneral": "General settings",
    "settingsAccount": "Account settings",
    "settingsAppearance": "Appearance settings",
    "help": "Help"
  },
  "WelcomePage": {
    "title": "Welcome",
    "greeting": "Welcome to\nSafe Cloud!",
    "description": "A reliable and convenient cloud storage solution for your files\nwith unlimited access from anywhere in the world",
    "links": {
      "login": "Login",
      "register": "Register"
    }
  },
  "AuthPage": {
    "title": {
      "login": "Login",
      "register": "Register",
      "activate": "Activation"
    },
    "labels": {
      "email": "Email",
      "password": "Password",
      "confirmPassword": "Confirm password",
      "name": "Name",
      "dontHaveAccount": "Don't have an account? <register>Register</register>",
      "alreadyHaveAccount": "Already have an account? <login>Login</login>"
    },
    "success": {
      "login": "You have successfully logged in",
      "register": "You have successfully registered"
    },
    "actions": {
      "login": "Login",
      "register": "Register",
      "logout": "Logout"
    },
    "errors": {
      "server": {
        "invalidCredentials": "Invalid email or password",
        "userAlreadyExists": "A user with this email already exists",
        "unknown": "An unknown error occurred"
      },
      "invalidEmail": "Invalid email",
      "nameMinLength": "Name must be at least {minLength} characters long",
      "nameMaxLength": "Name must be no more than {maxLength} characters long",
      "passwordMinLength": "Password must be at least {minLength} characters long",
      "passwordMaxLength": "Password must be no more than {maxLength} characters long",
      "passwordsNotMatch": "Passwords do not match"
    }
  },
  "HomePage": {
    "title": "Home"
  },
  "ProfilePage": {
    "title": "Profile",
    "lastUpdatedFolders": "Last updated folders",
    "lastUploadedFiles": "Last uploaded files"
  },
  "StoragePage": {
    "title": "My storage"
  },
  "SharedFilePage": {
    "title": "Shared files"
  },
  "SettingsPage": {
    "title": "Settings",
    "tabs": {
      "general": "General",
      "account": "Account",
      "appearance": "Appearance"
    },
    "account": {
      "changeUserName": "Change name",
      "changeUserEmail": "Change email",
      "changeUserPassword": "Change password",
      "save": "Save",
      "errors": {
        "nameMinLength": "Name must be at least {minLength} characters long",
        "nameMaxLength": "Name must be no more than {maxLength} characters long"
      }
    }
  },
  "HelpPage": {
    "title": "Help"
  }
};
export default messages;