// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "common": {
    "apply": "Apply",
    "cancel": "Cancel",
    "change": "Change",
    "save": "Save",
    "delete": "Delete",
    "properties": "Properties",
    "create": "Create"
  },
  "resolvedFileType": {
    "image": "Image",
    "video": "Video",
    "audio": "Audio",
    "document": "Document",
    "text": "Text",
    "source_code": "Source Code",
    "archive": "Archive",
    "exe": "Executable",
    "other": "Other",
    "model": "3D Model",
    "font": "Font",
    "plural": {
      "image": "Images",
      "video": "Videos",
      "audio": "Audio",
      "document": "Documents",
      "text": "Texts",
      "source_code": "Source Code",
      "archive": "Archives",
      "exe": "Executables",
      "model": "3D Models",
      "font": "Fonts",
      "other": "Other"
    }
  },
  "Navbar": {
    "home": "Home",
    "profile": "Profile",
    "storage": "Storage",
    "shared": "Shared Files",
    "settings": "Settings",
    "settingsGeneral": "General Settings",
    "settingsAccount": "Account Settings",
    "settingsAppearance": "Appearance Settings",
    "help": "Help"
  },
  "WelcomePage": {
    "title": "Welcome",
    "greeting": "Welcome to\nSafe Cloud!",
    "description": "A reliable and user-friendly cloud storage for your files\nwith unlimited access from anywhere in the world",
    "links": {
      "login": "Login",
      "register": "Register"
    }
  },
  "AuthPage": {
    "title": {
      "login": "Login",
      "register": "Register",
      "activate": "Activate Account"
    },
    "labels": {
      "email": "Email",
      "password": "Password",
      "confirmPassword": "Confirm Password",
      "name": "Name",
      "dontHaveAccount": "Don’t have an account? <register>Register</register>",
      "alreadyHaveAccount": "Already have an account? <login>Login</login>"
    },
    "success": {
      "login": "Successfully logged in",
      "register": "Successfully registered"
    },
    "actions": {
      "login": "Login",
      "register": "Register",
      "logout": "Logout"
    },
    "errors": {
      "server": {
        "invalidCredentials": "Invalid email or password",
        "userAlreadyExists": "A user with this email already exists",
        "unknown": "An unknown error occurred during authorization"
      },
      "invalidEmail": "Invalid email address",
      "nameMinLength": "Name must be at least {minLength, plural, =1 {# character} other {# characters}}",
      "nameMaxLength": "Name must be no more than {maxLength, plural, =1 {# character} other {# characters}}",
      "passwordMinLength": "Password must be at least {minLength, plural, =1 {# character} other {# characters}}",
      "passwordMaxLength": "Password must be no more than {maxLength, plural, =1 {# character} other {# characters}}",
      "passwordsNotMatch": "Passwords do not match"
    }
  },
  "HomePage": {
    "title": "Home",
    "foldersNotFound": "Nothing was found for your query",
    "youDontHaveFolders": "You don't have any folders yet",
    "CreateFormModal": {
      "title": "Create Folder",
      "success": "Folder created successfully",
      "labels": {
        "name": "Folder Name",
        "color": "Choose Folder Color"
      },
      "errors": {
        "server": {
          "unknown": "An unknown error occurred while creating the folder"
        },
        "nameMinLength": "Folder name must be at least {minLength, plural, =1 {# character} other {# characters}}",
        "nameMaxLength": "Folder name must be no more than {maxLength, plural, =1 {# character} other {# characters}}"
      }
    }
  },
  "ProfilePage": {
    "title": "Profile",
    "lastUpdatedFolders": "Recently Updated Folders",
    "lastUploadedFiles": "Recently Uploaded Files",
    "empty": "It's empty so far"
  },
  "StoragePage": {
    "title": "My Storage",
    "available": "Available",
    "capacity": "Total",
    "used": "Used",
    "empty": "You don't have any files yet"
  },
  "SharedFilePage": {
    "title": "Shared Files",
    "empty": "You don't have any shared files yet"
  },
  "SettingsPage": {
    "title": "Settings",
    "tabs": {
      "general": "General",
      "account": "Account",
      "appearance": "Appearance"
    },
    "account": {
      "avatar": {
        "title": "Change Avatar",
        "success": "Avatar changed successfully",
        "errors": {
          "invalidFile": "File must be an image ({format}) and no larger than {size}",
          "unknown": "An unknown error occurred while changing the avatar"
        }
      },
      "name": {
        "title": "Change Name",
        "success": "Name changed successfully",
        "errors": {
          "minLength": "Name must be at least {minLength, plural, =1 {# character} other {# characters}}",
          "maxLength": "Name must be no more than {maxLength, plural, =1 {# character} other {# characters}}",
          "server": {
            "unknown": "An unknown error occurred while changing the name"
          }
        }
      },
      "password": {
        "title": "Change Password",
        "description": "Enter your new password",
        "currentPassword": "Current Password",
        "newPassword": "New Password",
        "repeatNewPassword": "Repeat New Password",
        "errors": {
          "server": {
            "invalidCredentials": "Incorrect current password",
            "unknown": "An unknown error occurred while changing the password"
          },
          "minLength": "Password must be at least {minLength, plural, =1 {# character} other {# characters}}",
          "maxLength": "Password must be no more than {maxLength, plural, =1 {# character} other {# characters}}",
          "notMatch": "Passwords do not match"
        },
        "success": "Password changed successfully"
      },
      "email": {
        "title": "Change Email",
        "errors": {
          "invalid": "Invalid email address",
          "minLength": "Email must be at least {minLength, plural, =1 {# character} other {# characters}}",
          "maxLength": "Email must be no more than {maxLength, plural, =1 {# character} other {# characters}}",
          "server": {
            "unknown": "An unknown error occurred while changing the email",
            "userAlreadyExists": "User with this email already exists"
          }
        },
        "success": "Email changed successfully"
      },
      "delete": {
        "title": "Delete Account",
        "warning": "Are you sure you want to delete your account? All your data, including files and folders, will be permanently deleted",
        "success": "Account deleted successfully",
        "errors": {
          "unknown": "An unknown error occurred while deleting the account"
        }
      }
    },
    "appearance": {
      "theme": {
        "title": "Change Theme",
        "variants": {
          "dark": "Dark",
          "light": "Light",
          "system": "System"
        }
      }
    },
    "general": {
      "locale": {
        "title": "Interface Language",
        "item": {
          "ru": "Russian (Русский)",
          "en": "English (English)"
        }
      }
    }
  },
  "HelpPage": {
    "title": "Help",
    "questions": [
      {
        "q": "What is cloud storage?",
        "a": "Cloud storage is a service that allows you to store data online and access it from any internet-connected device."
      },
      {
        "q": "How to create an account?",
        "a": "Click the 'Register' button on the homepage and enter the required information."
      },
      {
        "q": "How to upload a file?",
        "a": "Go to the homepage, create a folder by clicking the appropriate button, then open the folder and drag a file into it, or click 'Add File' and select a file from your device."
      },
      {
        "q": "How much storage is available for free?",
        "a": "The free account provides 5 GB of storage space."
      },
      {
        "q": "Can I share files with others?",
        "a": "Yes, you can create public links to share files."
      },
      {
        "q": "How to permanently delete a file?",
        "a": "Right-click on the file and select 'Delete'. The file will be permanently deleted."
      },
      {
        "q": "Can I access my files without the internet?",
        "a": "No, an internet connection is required to access your files."
      },
      {
        "q": "How to change the password?",
        "a": "Go to account settings and select 'Change Password'."
      }
    ]
  },
  "FolderItem": {
    "contextMenu": {
      "open": "Open",
      "delete": "Delete",
      "properties": "Properties"
    },
    "modal": {
      "title": "Properties",
      "form": {
        "name": "Name",
        "color": "Color",
        "created": "Created",
        "updated": "Updated",
        "size": "Size",
        "update": {
          "errors": {
            "server": {
              "unknown": "An unknown error occurred while updating folder properties"
            },
            "nameMinLength": "Folder name must be at least {minLength, plural, =1 {# character} other {# characters}}",
            "nameMaxLength": "Folder name must be no more than {maxLength, plural, =1 {# character} other {# characters}}"
          },
          "success": "Folder properties updated successfully"
        },
        "delete": {
          "title": "Are you sure you want to delete this folder?",
          "warning": "This folder and all its contents will be permanently deleted",
          "errors": {
            "server": {
              "unknown": "An unknown error occurred while deleting the folder"
            }
          },
          "success": "Folder deleted successfully"
        }
      }
    }
  },
  "FileItem": {
    "contextMenu": {
      "download": "Download",
      "share": "Share",
      "delete": "Delete",
      "properties": "Properties"
    },
    "modal": {
      "title": "Properties",
      "form": {
        "name": "Name",
        "size": "Size",
        "type": "Type",
        "uploaded": "Uploaded",
        "updated": "Updated",
        "update": {
          "errors": {
            "server": {
              "unknown": "An unknown error occurred while updating file properties"
            },
            "nameMinLength": "File name must be at least {minLength, plural, =1 {# character} other {# characters}}",
            "nameMaxLength": "File name must be no more than {maxLength, plural, =1 {# character} other {# characters}}"
          },
          "success": "File properties updated successfully"
        },
        "delete": {
          "title": "Are you sure you want to delete this file?",
          "warning": "This file will be permanently deleted",
          "errors": {
            "server": {
              "unknown": "An unknown error occurred while deleting the file"
            }
          },
          "success": "File {name} deleted successfully"
        }
      }
    }
  },
  "FileUploadStatus": {
    "title": "File Upload Status",
    "button": "Cancel Upload"
  },
  "ShareFileForm": {
    "title": "Share File",
    "success": "File is now public",
    "label": "Make public",
    "errors": {
      "server": {
        "unknown": "An unknown error occurred while creating a public link"
      }
    }
  },
  "DropzoneFileUploader": {
    "errors": {
      "server": {
        "unknown": "An unknown error occurred while uploading file {name}",
        "notEnoughSpace": "Not enough space to upload file {name}"
      },
      "tooManyFiles": "Maximum number of files to upload: {limit}"
    },
    "started": "The upload of the {name} file has begun",
    "success": "File {name} uploaded successfully"
  },
  "NotFound": {
    "title": "404",
    "message": "This page does not exist"
  },
  "FolderPage": {
    "empty": "Folder is empty but you can upload a new file"
  }
};
export default messages;