// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "Navbar": {
    "home": "Home",
    "profile": "Profile",
    "storage": "Storage",
    "shared": "Shared files",
    "settings": "Settings",
    "settingsGeneral": "General settings",
    "settingsAccount": "Account settings",
    "settingsAppearance": "Appearance settings",
    "help": "Help"
  },
  "WelcomePage": {
    "title": "Welcome",
    "greeting": "Welcome to\nSafe Cloud!",
    "description": "A reliable and convenient cloud storage solution for your files\nwith unlimited access from anywhere in the world",
    "links": {
      "login": "Login",
      "register": "Register"
    }
  },
  "AuthPage": {
    "title": {
      "login": "Login",
      "register": "Register",
      "activate": "Activation"
    },
    "labels": {
      "email": "Email",
      "password": "Password",
      "confirmPassword": "Confirm password",
      "name": "Name",
      "dontHaveAccount": "Don't have an account? <register>Register</register>",
      "alreadyHaveAccount": "Already have an account? <login>Login</login>"
    },
    "success": {
      "login": "You have successfully logged in",
      "register": "You have successfully registered"
    },
    "actions": {
      "login": "Login",
      "register": "Register",
      "logout": "Logout"
    },
    "errors": {
      "server": {
        "invalidCredentials": "Invalid email or password",
        "userAlreadyExists": "A user with this email already exists",
        "unknown": "An unknown error occurred"
      },
      "invalidEmail": "Invalid email",
      "nameMinLength": "Name must be at least {minLength} characters long",
      "nameMaxLength": "Name must be no more than {maxLength} characters long",
      "passwordMinLength": "Password must be at least {minLength} characters long",
      "passwordMaxLength": "Password must be no more than {maxLength} characters long",
      "passwordsNotMatch": "Passwords do not match"
    }
  },
  "HomePage": {
    "title": "Home"
  },
  "ProfilePage": {
    "title": "Profile",
    "lastUpdatedFolders": "Last updated folders",
    "lastUploadedFiles": "Last uploaded files"
  },
  "StoragePage": {
    "title": "My storage",
    "available": "Available",
    "capacity": "Total",
    "used": "Used",
    "resolvedFileType": {
      "image": "Image",
      "video": "Video",
      "audio": "Audio",
      "document": "Document",
      "text": "Text",
      "source_code": "Source Code",
      "archive": "Archive",
      "exe": "Executable File",
      "other": "Other",
      "model": "3D Model",
      "font": "Font",
      "plural": {
        "image": "Images",
        "video": "Videos",
        "audio": "Audio",
        "document": "Documents",
        "text": "Texts",
        "source_code": "Source Code",
        "archive": "Archives",
        "exe": "Executable Files",
        "model": "3D Models",
        "font": "Fonts",
        "other": "Other"
      }
    }
  },
  "SharedFilePage": {
    "title": "Shared files"
  },
  "SettingsPage": {
    "title": "Settings",
    "tabs": {
      "general": "General",
      "account": "Account",
      "appearance": "Appearance"
    },
    "account": {
      "avatar": {
        "title": "Change avatar",
        "success": "You have successfully changed your avatar",
        "errors": {
          "invalidFile": "The file must be an image ({format}) and no larger than {size}",
          "unknown": "An unknown error occurred while changing the avatar"
        }
      },
      "name": {
        "title": "Change Name",
        "success": "You have successfully changed your name",
        "errors": {
          "minLength": "Name must be at least {minLength} characters long",
          "maxLength": "Name must be no more than {maxLength} characters long"
        }
      },
      "password": {
        "title": "Change Password",
        "description": "Enter a new password",
        "currentPassword": "Current password",
        "newPassword": "New password",
        "repeatNewPassword": "Repeat new password",
        "errors": {
          "minLength": "Password must be at least {minLength} characters long",
          "maxLength": "Password must be no more than {maxLength} characters long",
          "notMatch": "Passwords do not match"
        },
        "cancel": "Cancel"
      },
      "email": {
        "title": "Change Email",
        "errors": {
          "invalid": "Invalid email address"
        } 
      },
      "delete": {
        "title": "Deleting an account",
        "warning": "Are you sure you want to delete your account? All your data, including files and folders, will be permanently deleted.",
        "cancel": "Cancel",
        "confirm": "Delete"
      },
      "submit": "Save",
      "change": "Change"
    },
    "appearance": {
    "theme": {
        "title": "Change Theme",
        "variants": {
          "dark": "Dark",
          "light": "Light",
          "system": "System"
        }
      }
    },
    "general": {
      "locale": {
        "title": "App language",
        "item": {
          "ru": "Russian (Русский)",
          "en": "English (English)"
        }
      }
    }
  },
  "HelpPage": {
    "title": "Help",
    "questions": [
      {
        "q": "What is cloud storage?",
        "a": "Cloud storage is a service that allows you to store data online and access it from any device connected to the internet."
      },
      {
        "q": "How secure is my data?",
        "a": "We use industry-standard encryption and security protocols to protect your data both in transit and at rest."
      },
      {
        "q": "Can I access my files offline?",
        "a": "Yes, you can mark files for offline access and they will be synced to your device."
      },
      {
        "q": "How much storage do I get for free?",
        "a": "We offer 10 GB of free storage to all new users. You can upgrade at any time for more space."
      },
      {
        "q": "How do I share files with others?",
        "a": "You can generate a shareable link or invite users via email with customizable access permissions."
      },
      {
        "q": "Can I recover deleted files?",
        "a": "Yes, deleted files are moved to the Trash and can be restored within 30 days."
      },
      {
        "q": "What file types are supported?",
        "a": "Our cloud storage supports all common file types including documents, images, videos, and archives."
      },
      {
        "q": "Is there a mobile app available?",
        "a": "Yes, our mobile app is available for both iOS and Android, offering full access to your files on the go."
      },
      {
        "q": "How can I upgrade my storage plan?",
        "a": "You can upgrade your plan at any time from the account settings page under the 'Billing' section."
      },
      {
        "q": "Can I collaborate with others on files?",
        "a": "Yes, you can grant editing permissions to other users and collaborate in real time on documents."
      },
      {
        "q": "How do I contact support?",
        "a": "You can contact our support team via the Help Center or by submitting a ticket through your account dashboard."
      },
      {
        "q": "What happens if I exceed my storage limit?",
        "a": "If you exceed your storage quota, uploads will be paused until you delete files or upgrade your plan."
      },
      {
        "q": "Are there any bandwidth limits?",
        "a": "There are no limits on bandwidth for standard use, but excessive usage may be subject to fair use policies."
      },
      {
        "q": "Can I use cloud storage for backups?",
        "a": "Yes, our service is ideal for backing up important files and syncing them across devices."
      },
      {
        "q": "Is version history available?",
        "a": "Yes, we store previous versions of your files for up to 30 days, allowing you to revert if needed."
      }
    ]
  },
  "FolderItem": {
    "contextMenu": {
      "open": "Open",
      "delete": "Delete",
      "properties": "Properties"
    },
    "modal": {
      "title": "Properties"
    }
  }
};
export default messages;